#!/bin/bash

#start swwww
swww query || swww init
wallpaper_dir="$HOME/.wallpapers"
wallpaper=$(ls $wallpaper_dir | shuf --random-source=/dev/urandom -n 1)
swaybg -m fill -i "$wallpaper_dir/$wallpaper"
